swagger: '2.0'
info:
  version: latest
  title: S3 API - ACL Operations
host: s3.seagate.com
schemes:
  - http
  - https
paths:
  '/{bucket_name}':
    get:
      tags:
        - Get Bucket ACL
      parameters:
        - name: bucket_name
          in: path
          type: string
          required: true
        - name: acl
          in: query
          type: string
          required: true
        - name: User-Agent
          in: header
          description: Header to identify application, it's version number and programming language.
          type: string
          required: true
        - name: X-Amz-Date
          in: header
          description: Date header used to create the signature.
          type: string
          required: true
        - name: X-Amz-Content-SHA256
          in: header
          description: This header value informs whether s3 request signed or not.
          type: string
          required: true
        - name: Authorization
          in: header
          description: >-
            This Header contains credentials to authorize a User-Agent with
            server.
          type: string
          required: true
      produces:
        - application/xml
      responses:
        '200':
          description: OK
          schema:
            type: object
            xml:
              name: AccessControlPolicy
            properties:
              Owner:
                type: object
                properties:
                  ID:
                    type: string
                  DisplayName:
                    type: string
              AccessControlList:
                type: object
                properties:
                  Grant:
                    type: object
                    properties:
                      Grantee:
                        type: object
                        properties:
                          ID:
                            type: string
                          DisplayName:
                            type: string
                      Permission:
                        type: string
          headers:
            Content-Type:
              type: string
            Content-Length:
              type: integer
            x-amz-request-id:
              type: string
            Server:
              type: string
    put:
      tags:
        - Put Bucket ACL
      parameters:
        - name: bucket_name
          in: path
          type: string
          required: true
        - name: acl
          in: query
          type: string
          required: true
        - name: x-amz-grant-full-control
          in: header
          description: Allows grantee the read, write, read ACP, and write ACP permissions on the bucket.
          type: string
        - name: x-amz-grant-read
          in: header
          description: Allows grantee to list the objects in the bucket.
          type: string
        - name: x-amz-grant-read-acp
          in: header
          description: Allows grantee to read the bucket ACL.
          type: string
        - name: x-amz-grant-write
          in: header
          description: Allows grantee to create new objects in the bucket.
          type: string
        - name: x-amz-grant-write-acp
          in: header
          description: Allows grantee to write the ACL for the applicable bucket.
          type: string
        - name: Content-MD5
          in: header
          description: This header provides message integrity check.
          type: string
          required: true
        - name: User-agent
          in: header
          description: >-
            Header to identify application, it's version number and programming
            language.
          type: string
          required: true
        - name: X-Amz-Date
          in: header
          description: Date header used to create the signature.
          type: string
        - name: X-Amz-Content-SHA256
          in: header
          description: This header value informs whether s3 request signed or not.
          type: string
          required: true
        - name: Authorization
          in: header
          description: >-
            This Header contains credentials to authorize a User-Agent with
            server.
          type: string
          required: true
        - name: Content-Length
          in: header
          description: The Content-Length header indicates the size of the message body, in bytes.
          type: string
          required: true
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          headers:
            Content-Length:
              type: integer
            x-amz-request-id:
              type: string
            Content-Type:
              type: string
            Server:
              type: string
  '/{bucket_name}/{object_name}':
    get:
      tags:
        - Get Object ACL
      parameters:
        - name: bucket_name
          in: path
          type: string
          required: true
        - name: object_name
          in: path
          type: string
          required: true
        - name: acl
          in: query
          type: string
          required: true
        - name: User-Agent
          in: header
          description: >-
            Header to identify application, it's version number and programming
            language.
          type: string
          required: true
        - name: X-Amz-Date
          in: header
          description: Date header used to create the signature.
          type: string
          required: true
        - name: X-Amz-Content-SHA256
          in: header
          description: This header value informs whether s3 request signed or not.
          type: string
          required: true
        - name: Authorization
          in: header
          description: >-
            This Header contains credentials to authorize a User-Agent with
            server.
          type: string
          required: true
      produces:
        - application/xml
      responses:
        '200':
          description: OK
          schema:
            type: object
            xml:
              name: AccessControlPolicy
            properties:
              Owner:
                type: object
                properties:
                  ID:
                    type: string
                  DisplayName:
                    type: string
              AccessControlList:
                type: object
                properties:
                  Grant:
                    type: object
                    properties:
                      Grantee:
                        type: object
                        properties:
                          ID:
                            type: string
                          DisplayName:
                            type: string
                      Permission:
                        type: string
          headers:
            Content-Type:
              type: string
            Content-Length:
              type: integer
            x-amz-request-id:
              type: string
            Server:
              type: string
    put:
      tags:
        - Put Object ACL
      parameters:
        - name: bucket_name
          in: path
          type: string
          required: true
        - name: object_name
          in: path
          type: string
          required: true
        - name: acl
          in: query
          type: string
          required: true
        - name: x-amz-grant-full-control
          in: header
          description: Allows grantee the read, write, read ACP, and write ACP permissions on the bucket.
          type: string
        - name: x-amz-grant-read
          in: header
          description: Allows grantee to list the objects in the bucket.
          type: string
        - name: x-amz-grant-read-acp
          in: header
          description: Allows grantee to read the bucket ACL.
          type: string
        - name: x-amz-grant-write
          in: header
          description: Allows grantee to create new objects in the bucket.
          type: string
        - name: x-amz-grant-write-acp
          in: header
          description: Allows grantee to write the ACL for the applicable bucket.
          type: string
        - name: Content-MD5
          in: header
          description: >-
            This header is used to indicate the original media type of the
            resource.
          type: string
          required: true
        - name: User-Agent
          in: header
          description: >-
            Header to identify application, it's version number and programming
            language.
          required: true
          type: string
        - name: X-Amz-Date
          in: header
          description: Date header used to create the signature.
          required: false
          type: string
        - name: X-Amz-Content-SHA256
          in: header
          description: This header value informs whether s3 request signed or not.
          required: true
          type: string
        - name: Authorization
          in: header
          description: >-
            This Header contains credentials to authorize a User-Agent with
            server.
          required: true
          type: string
        - name: Content-Length
          in: header
          description: >-
            This header indicates the size of the message body, in bytes, sent
            to the recipient.
          type: string
          required: true
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            type: object
          headers:
            Content-Length:
              type: integer
            x-amz-request-id:
              type: string
            Content-Type:
              type: string
            Server:
              type: string
