swagger: '2.0'
info:
  version: latest
  title: S3 API - Complete multipart upload
host: s3.seagate.com
schemes:
  - http
  - https
paths:
  /{bucket_name}/{object_name}:
    post:
      tags:
        - Complete multipart upload
      parameters:
        - name: bucket_name
          in: path
          type: string
          required: true
        - name: object_name
          in: path
          type: string
          required: true
        - name: uploadId
          in: query
          type: string
          required: true
        - name: User-Agent
          in: header
          description: Header to identify application, it's version number and programming language.
          type: string
          required: true
        - name: X-Amz-Date
          in: header
          description: Date header used to create the signature.
          type: string
          required: true
        - name: X-Amz-Content-SHA256
          in: header
          description: This header value informs whether s3 request signed or not.
          type: string
          required: true
        - name: Authorization
          in: header
          description: >-
            This Header contains credentials to authorize a User-Agent with
            server.
          type: string
          required: true
        - name: Content-Length
          in: header
          description: This header indicates the size of the message body, in bytes, sent
            to the recipient.
          required: true
          type: string
      produces:
        - application/xml
      responses:
        200:
          description: OK
          schema:
            type: object
            xml:
              name: CompleteMultipartUploadResult
            properties:
              Location:
                type: string
              Bucket:
                type: string
              Key:
                type: string
              ETag:
                type: string
          headers:
            x-amz-request-id:
              type: string
            Content-Length:
              type: integer
            Content-Type:
              type: string
            Server:
              type: string
